### ISSUE TITLE
Parsing a Color Correction node with valid saturation value will sometimes fail

### ISSUE THREAD

**Issue by gregcotten** [shidarin/cdl_convert#47]
For a sat node that looks like below - which is, admittedly, very dumb looking.
```xml
<SatNode>
	<Saturation> 1 </Saturation>
</SatNode>
```

I get this error:
```
Error setting saturation with value: " 1 .0". Value is not a number.
Traceback (most recent call last):
  File "/Users/gregcotten/Library/Developer/Xcode/DerivedData/Lattice-hbhjbgnjvczkbcfgkxhrjqvqoaks/Build/Products/Debug-Standalone/Lattice.app/Contents/Resources/cdl_convert/cdl_convert.py", line 294, in <module>
    main()
  File "/Users/gregcotten/Library/Developer/Xcode/DerivedData/Lattice-hbhjbgnjvczkbcfgkxhrjqvqoaks/Build/Products/Debug-Standalone/Lattice.app/Contents/Resources/cdl_convert/cdl_convert.py", line 222, in main
    color_decisions = parse.parse_file(filepath, filetype_in)
  File "cdl_convert/parse.py", line 724, in parse_file
    return INPUT_FORMATS[filetype](filepath)
  File "cdl_convert/parse.py", line 449, in parse_cdl
    if not cdl.parse_xml_color_decisions(root):
  File "cdl_convert/collection.py", line 633, in parse_xml_color_decisions
    color_decision.parse_xml_color_decision(cd_node)
  File "cdl_convert/decision.py", line 581, in parse_xml_color_decision
    if not self.parse_xml_color_correction(xml_element):
  File "cdl_convert/decision.py", line 550, in parse_xml_color_correction
    self.cc = parse.parse_cc(cc_elem)
  File "cdl_convert/parse.py", line 336, in parse_cc
    cdl.sat = find_required(sat_xml, ['Saturation']).text
  File "cdl_convert/correction.py", line 366, in sat
    self.sat_node.sat = sat_value
  File "cdl_convert/correction.py", line 522, in sat
    value = self._check_single_value(value, 'saturation')
  File "cdl_convert/base.py", line 457, in _check_single_value
    value = to_decimal(value, name)
  File "cdl_convert/utils.py", line 186, in to_decimal
    value=value
TypeError: Error setting saturation with value: " 1 .0". Value is not a number.
```

I think the culprit is [this](https://github.com/shidarin/cdl_convert/blob/857313041448061fc6b92e602169423e90cf590a/cdl_convert/utils.py#L176). Probably don't need to be adding '.0' to the value.
```python
if '.' not in value:
     value.strip() += '.0'
```

**Comment by shidarin** [comment]
This is part of the code that handles the decimal conversion. Without it, python starts changing the numbers during conversion. We weren't stripping any whitespace off incoming strings, as you ran into. Added a strip line, updated tests.

**Comment by gregcotten** [comment]
Crazy that the decimal converter requires a ".0" at the end if there is no decimal point in the number!

**Comment by shidarin** [comment]
It's a jenky homemade decimal as string system- not python's official one. Python's official one has some un-CDL friendly habits like scientific notation.

**Comment by gregcotten** [comment]
I have the same problem with NSNumber in Cocoa. Frustrating!
