### ISSUE TITLE
runtime errors on OSX 10.10.5

### ISSUE THREAD

**Issue by bengervais** [shidarin/cdl_convert#50]
After installing, CDL_Convert seems to error out upon execution. With the following error:

```
qc02:test qc2$ cdl_convert -i cdl -o cc --single bla.cdl
Traceback (most recent call last):
  File "/usr/local/bin/cdl_convert", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/cdl_convert/cdl_convert.py", line 222, in main
    color_decisions = parse.parse_file(filepath, filetype_in)
  File "/usr/local/lib/python2.7/site-packages/cdl_convert/parse.py", line 712, in parse_file
    return INPUT_FORMATS[filetype](filepath)
  File "/usr/local/lib/python2.7/site-packages/cdl_convert/parse.py", line 419, in parse_cdl
    root = _remove_xmlns(input_file)
  File "/usr/local/lib/python2.7/site-packages/cdl_convert/parse.py", line 665, in _remove_xmlns
    return ElementTree.fromstring(xml_string)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: syntax error: line 1, column 0
qc02:test qc2$

```

Occurs on multiple machines, all same OS version, and all running python 2.7.10 installed via homebrew.

**Comment by shidarin** [comment]
Could you send me the cdl you're using?

 -Sean Wallitsch

**Comment by bengervais** [comment]
no problem - attached.

-ben

Ben Gervais
Production Systems Supervisor & Engineer
Billy Lynn's Long Halftime Walk - Tristar Productions
+1 818 274 2371 (US Cell)
+1 416 951 1980 (Canada Cell)
bengervais@gmail.com
